### ISSUE TITLE
Overhaul

### ISSUE THREAD

**Issue by igoynawamreh** [bantenprov/document-management-system#38]
# Overhaul

### Reorganize and rename files and folder

``` plaintext
document-management-system/
├── document/
│ ├── aplikasi
│ | └── [Konten]
│ ├── sop
│ | └── [Konten]
│ └── konsep
│   └── [Konten]
└── [Jekyll files and more]
```

**URL**:

- `dms.example.com/document/aplikasi/<konten>`
- `dms.example.com/document/sop-online/<konten>`
- `dms.example.com/document/konsep/<konten>`

### Updates

- Redesign
- Drop `img.bangunbanten.com`
- Fix typo
- And more

**Comment by andri-sudarmawijaya** [comment]
Thanks for your correction, this repository is heavily under construction. we will correct at the nest pull request

**Comment by igoynawamreh** [comment]
@andri-sudarmawijaya

**Comment by igoynawamreh** [comment]
Saya nunggu datanya lengkap dulu, biar langsung dipindahkan. Setelah selesai Saya akan melakukan PR. Kalau sekarang nanti datanya berantakan.
